### PR TITLE
Invert analog + mapper save versioning

### PR DESCRIPTION
**Pull request by ahnada**
Implements issue #51.

Also added save versioning so people won't lose their configuration on upgrade.

### CODE REVIEW

**Comment by decafcode** [comment]
Looks okay to me. The versioning problem seems a bit tricky, I maybe wouldn't try to stuff a magic FourCC at the start of the file, instead I would use a different file name that doesn't contain a version in the file name, and define a new format for that new-style file. If geninput is asked to load its config, check for an old-style config file and if it loads one then write out a migrated new file. 

Of course, it's more work to do it that way. Up to you which direction you choose to go, of course.

**Comment by ahnada** [comment]
Added code to read from the old saves but write out to a new filename without the version string appended.

Also here are some concerns that were brought up on Discord:
- People might downgrade versions and the new FourCC might cause the program to immediately crash
The old code does treat the FourCC is a count and the loading code will soon try to read in a ridiculously large string (1+ gb in my test). Luckily either the allocation will fail or the subsequent fread fails, and the program will happily abort the load and start clean.
- Loader for the new format should check the version field and only load versions >= 1
The loader already knows how to correctly read the old version files so I didn't really see a point to this. If people want to rename old saves to the new filename or new saves to the old filename, the program will properly parse it.
- Make a copy of the current config as a ".back" before any upgrades
The new saves are using a new filename and it doesn't delete the old files.

**Comment by icex2** [comment]
lgtm, what do you think @decafcode ?

**Comment by icex2** [comment]
> lgtm, what do you think @decafcode ?

Talked to him and he said "it's fine"

**Pull request merged**
